import type { DatasetType } from "./datasets.js";
import type { AnomalyEvidence } from "./intelligence.js";

// Ramesh — the Rameshwaram Intelligence Assistant.
//
// Ramesh is a DETERMINISTIC query engine, not a generative model. Questions are
// parsed into a structured intent, the answer is computed by the same SQL/JS
// aggregations that power the dashboard, and the reply is templated from those
// numbers. This is a deliberate architectural choice:
//   * numbers can never be hallucinated -- they are computed, not predicted;
//   * every answer is reproducible: same data + same question => same output;
//   * the calculation shown IS the calculation performed;
//   * uploaded file content is never fed to a model as instructions, so
//     prompt injection via a spreadsheet cell is structurally impossible.

// User-facing name is "Ask Anything" (see RameshWidget.tsx) -- this constant
// keeps its original name since it's an internal identifier used across
// files, but its value is what actually renders to users.
export const RAMESH_IDENTITY = "Ask Anything — Rameshwaram QSR Dashboard";

export const RAMESH_OFF_TOPIC_REPLY =
  "I'm Ask Anything, the assistant for the Rameshwaram QSR Dashboard. I can only answer using business data from this dashboard.";

export type RameshIntent =
  | "total_sales"
  | "total_production"
  | "total_wastage"
  | "top_product"
  | "bottom_product"
  | "peak_hour"
  | "compare_dates"
  | "compare_datasets"
  | "wastage_reason"
  | "variance_explain"
  | "anomaly_explain"
  | "trend"
  | "executive_analysis"
  | "root_cause"
  | "efficiency"
  | "shift_performance"
  | "outlet_performance"
  | "product_performance"
  | "reconciliation"
  | "data_coverage"
  | "help"
  | "off_topic"
  | "unsupported"
  /** A general, non-data-grounded reply generated by the Gemini-backed Ask Anything integration. */
  | "general";

export interface RameshQuery {
  question: string;
  /** Dashboard filter context, so Ramesh answers within what the user is looking at. */
  context?: {
    from?: string;
    to?: string;
    product?: string;
    outlet?: string;
    shift?: string;
  };
}

/** What data the answer was computed from -- shown verbatim under "Data Used". */
export interface RameshDataUsed {
  datasets: DatasetType[];
  businessDateFrom: string | null;
  businessDateTo: string | null;
  product: string | null;
  outlet: string | null;
  shift: string | null;
  recordCount: number;
}

/** One line of arithmetic, rendered as shown. */
export interface RameshCalculationStep {
  label: string;
  expression: string;
  result: string;
}

/**
 * One ranked finding inside an analytical answer. Every field is filled from
 * computed aggregates -- the numbers live in `magnitude` and `evidence`, never
 * only in prose.
 */
export interface RameshInsightLine {
  rank: number;
  severity: "high" | "medium" | "low" | "info";
  category: string;
  /** WHAT happened, with the number in it. */
  headline: string;
  /** HOW MUCH -- quantified magnitude. */
  magnitude: string;
  /** WHEN / WHERE / WHICH PRODUCT. */
  scope: string;
  /** Measurable business impact. */
  impact: string;
  /** Only what the data supports; may state what to verify instead. */
  action: string;
  evidence: AnomalyEvidence[];
  drilldownQuery: Record<string, string> | null;
}

export interface RameshAnswer {
  intent: RameshIntent;
  /** Direct answer. Never contains a number that isn't in `calculation`/`dataUsed`. */
  answer: string;
  dataUsed: RameshDataUsed | null;
  calculation: RameshCalculationStep[];
  conclusion: string;
  /** Ranked findings for analytical/executive questions. Empty for simple lookups. */
  insights: RameshInsightLine[];
  evidence: AnomalyEvidence[];
  /** Query params for the "View records" drill-down into the Data Explorer. */
  drilldownQuery: Record<string, string> | null;
  /** True when Ramesh declined for lack of data rather than answering. */
  insufficientData: boolean;
  /** Set when the question was rejected as off-topic or as an injection attempt. */
  refusalReason: "off_topic" | "injection_attempt" | "not_configured" | "provider_error" | null;
  /** Follow-up questions Ramesh can actually answer from the current data. */
  suggestions: string[];
}

export interface RameshMessage {
  id: string;
  role: "user" | "ramesh";
  text: string;
  answer?: RameshAnswer;
  timestamp: string;
}
